name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run tests
        run: |
          npm ci
          npx lerna bootstrap
          npm test
